---
# Source: base/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: wkfn-spring-app
data:
  CHANNEL: IBM.APP.SVRCONN
  CONNECTION_NAME: qm1-ibm-wkfn.staging.svc.cluster.local(1414)
  QM: QM1
  QUEUE_NAME: IBM.DEMO.Q
  APP_NAME: wkfn-SPRING-APP
